### PR TITLE
Update to SC 4.4.7

### PR DESCRIPTION
**Pull request by DylanLacey**

### CODE REVIEW

**Comment by halkeye** [comment]
4.4.8 is supposed to come out this week.

@saucy-aseem and @richard-sl are currently keeping an eye on this, but i don't know if they are watching the repo yet.

**Comment by DylanLacey** [comment]
OK, well, whether that happens or not, this updates ci-sauce to at least be a _little_ more contemporary.

I've also updated saucelabs/sauce-java to reference the latest already released version of this.  `1.129-SNAPSHOT` was unreleased so I've pointed it at `1.128`.

**Comment by bootstraponline** [comment]
looks like 4.4.8 is out?

**Comment by DylanLacey** [comment]
Ping @saucy-aseem and @richard-sl

**Comment by valfirst** [comment]
@DylanLacey, @halkeye, @bootstraponline, master branch is already [updated to sauce connect 4.4.9](https://github.com/saucelabs/ci-sauce/commit/a7f3187442f043b5e90057c75338c507da074644). `ci-sauce:1.129` is released.

**Pull request closed without merging**
