### PR TITLE
Bumping Sauce Connect version to 4.4.4 to help resolve glibc 2.12 issues

### PR DESCRIPTION
**Pull request by imuchnik**
https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy+Version+4.4.4

### CODE REVIEW

**Comment by vccabral** [comment]
LGTM

**Comment by OrlandoSoto** [comment]
👍

**Comment by OrlandoSoto** [comment]
@halkeye review please?

**Comment by halkeye** [comment]
I really appreciate this PR, I really do. But I don't feel comfortable including binaries from other people. I hope you understand.

This is now merged in 6ae1422 and i'll am releasing 1.125 right now

**Comment by halkeye** [comment]
ci-sauce-1.125 is now out

**Comment by imuchnik** [comment]
@halkeye No worries.  As long as there is a new release, we have way to move forward.  Thanks for a quick turn around.

**Comment by OrlandoSoto** [comment]
thanks @halkeye !

**Pull request closed without merging**
