### PR TITLE
Update ci-sauce java library to take advantage of more sauce rest apis

### PR DESCRIPTION
**Pull request by halkeye**
Fix up unit tests so they run again
ignore compiled output in git

### CODE REVIEW

**Comment by halkeye** [comment]
@mehmetg @mehmetg-sauce any suggestions on how to do .equals test?

**Comment by mehmetg** [comment]
This may be a bit of a overkill, but it's easy enough and it'd be easy to implement with some helpers. It's plain and does not require complicated combinatorics. :) I would be happy to contribute. 

- Content Check:
 - For failures:
I can make a list of random strings and test pass and fail i.e generate test to pass and then inject failure and walk it. Looking at the code shifting the mismatch is enough. No need to binary count mismatches.
e.g. {A, A, A} ==  {A, A, B} ,
       {A, A, A} ==  {A, B, A}.
       {A, A, A} ==  {B, A, A}. 

 - For passing cases I'd go after counting up the null field. For coverage you need to do the count as pass fall through and does not return immediately.

- Object type check similar test cases like above:
 - pass 
 - fail
 - null

- Reference check o.equals(o) expect pass

**Comment by halkeye** [comment]
yea i'd love help with some more test. I'm pretty happy with the current coverage 'cause it'll keep track of changes to api and stuff. I'm thinking I might merge this as is, and we can open a new PR with more

**Comment by mehmetg** [comment]
I agree the proposed test is a bit of an overkill, but would be a fun example when we have time.

**Pull request merged**
