### PR TITLE
Switch to saucerest

### PR DESCRIPTION
**Pull request by halkeye**
Switch appium, webdriver and selenium browser lists to use the saucerest apis so they are all in one central location.

Repair unit tests so they pass again

### CODE REVIEW

**Comment by halkeye** [comment]
cc @moizjv

**Comment by moizjv** [comment]
https://github.com/saucelabs/ci-sauce/blob/0d6ca8081cf4f7a65d25f608c9b940ef4e1c272f/src/main/java/com/saucelabs/ci/SauceLibraryManager.java#L21, can we change this line too?

**Comment by halkeye** [comment]
I'll check when I get home. Is it already in saucerest?

I suspect it shouldn't be an issue

**Comment by halkeye** [comment]
Oh you essentially mean everything in
https://github.com/saucelabs/ci-sauce/blob/0d6ca8081cf4f7a65d25f608c9b940ef4e1c272f/src/main/java/com/saucelabs/ci/SauceFactory.java
?

On Tue, Nov 3, 2015 at 4:48 PM, Gavin Mogan <gavin@saucelabs.com> wrote:

> I'll check when I get home. Is it already in saucerest?
>
> I suspect it shouldn't be an issue
> On Nov 3, 2015 4:39 PM, "Moiz Virani" <notifications@github.com> wrote:
>
>>
>> https://github.com/saucelabs/ci-sauce/blob/0d6ca8081cf4f7a65d25f608c9b940ef4e1c272f/src/main/java/com/saucelabs/ci/SauceLibraryManager.java#L21,
>> can we change this line too?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/saucelabs/ci-sauce/pull/14#issuecomment-153534556>.
>>
>


-- 


*Gavin MoganSoftware Developer*

Sauce Labs <http://saucelabs.com/> | Sauce blog <http://sauceio.com/>

Talk to us anytime:  <https://twitter.com/saucelabs>
<https://www.linkedin.com/company/sauce-labs>
<https://plus.google.com/+SauceLabs_Official/posts>
<https://www.facebook.com/saucelabs>

**Comment by moizjv** [comment]
Ohh i see what you are saying. Do you think we can completely do away with rest factory and use saucerest?

**Pull request closed without merging**
